services:
  api-gateway:
    image: api-gateway
    ports:
      - 9999:9999
    environment:
      - eureka.client.serviceUrl.defaultZone=http://discovery-service:8761/eureka
    depends_on:
      - discovery-service

  product-service:
    image: product-service
    ports:
      - 6001:6001
    environment:
      - eureka.client.serviceUrl.defaultZone=http://discovery-service:8761/eureka
    depends_on:
      - mongodb
      - discovery-service

  discovery-service:
    image: discoveryserver
    ports:
      - 8761:8761
    mem_limit: 700m
    depends_on:
      - keycloak

  #docker run -p 8181:8181 -e KEYCLOAK_ADMIN=admin -e KEYCLOAK_ADMIN_PASSWORD=admin quay.io/keycloak/keycloak:22.0.5 start-dev
  keycloak:
    image: quay.io/keycloak/keycloak
    ports:
      - 8080:8080
    mem_limit: 700m
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      #KEYCLOAK_HTTP_PORT: 8181
    command:
      - start-dev

  mongodb:
    image: mongo
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root

  
  zookeeper:
    image: confluentinc/cp-zookeeper
    ports:
      - 2181:2181
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181

  kafka:
    image: confluentinc/cp-kafka
    ports:
      - 9092:9092
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_INTERNAL:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092,PLAINTEXT_INTERNAL://broker:29092
      KAFKA_BROKER_ID: 1
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1

  kafka-manager:
    image: hlebalbau/kafka-manager
    ports:
      - 9000:9000
    environment:
      ZK_HOSTS: zookeeper:2181
    depends_on:
      - kafka