services:

  discovery-service:
    image: hasanemrealkan/discoveryserver
    ports:
      - 8761:8761
    mem_limit: 700m

  #docker run -p 8181:8181 -e KEYCLOAK_ADMIN=admin -e KEYCLOAK_ADMIN_PASSWORD=admin quay.io/keycloak/keycloak:22.0.5 start-dev
  keycloak:
    image: quay.io/keycloak/keycloak
    ports:
      - 8181:8080
    mem_limit: 700m
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KEYCLOAK_HTTP_PORT: 8181
      KEYCLOAK_IMPORT: /path/to/your/realm-export.json
    command:
      - start-dev
    volumes:
      - ./path/to/your/realm-export.json:/path/to/your/realm-export.json

  #api-gateway hata verdiginden dolayi docker hub'a atmadik.
  order-service:
    image: orderservice
    ports:
      - 8083:8083
    mem_limit: 700m
    depends_on:
      - api-gateway
      - postgres
  #api-gateway hata verdiginden dolayi docker hub'a atmadik.
  product-service:
    image: productservice
    ports:
      - 8084:8084
    mem_limit: 700m
    depends_on:
      - api-gateway
      - mongo

  #api-gateway hata verdiginden dolayi docker hub'a atmadik.
  api-gateway:
    image: apigateway
    ports:
      - "8888:8888"
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://discovery-service:8761/eureka/
      - SPRING_APPLICATION_NAME=api-gateway
      - MANAGEMENT_ENDPOINTS_WEB_EXPOSURE_INCLUDE=info
      - SPRING_CLOUD_GATEWAY_ROUTES[0]_ID=product-service
      - SPRING_CLOUD_GATEWAY_ROUTES[0]_URI=lb://product-service
      - SPRING_CLOUD_GATEWAY_ROUTES[0]_PREDICATES[0]=Path=/api/v1/products/**
      - SPRING_CLOUD_GATEWAY_ROUTES[1]_ID=order-service
      - SPRING_CLOUD_GATEWAY_ROUTES[1]_URI=lb://order-service
      - SPRING_CLOUD_GATEWAY_ROUTES[1]_PREDICATES[0]=Path=/api/v1/orders/**
      - SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_ISSUER-URI=http://keycloak:8181/realms/turkcell-microservices
    depends_on:
      - discovery-service
      - keycloak

  #docker run --name mongo -d mongodb/mongodb-community-server:latest
  mongo:
    image: mongo
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
      - mongo_data:/data/db

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8282:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_BASICAUTH_USERNAME: admin
      ME_CONFIG_BASICAUTH_PASSWORD: admin
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/

  postgres:
    image: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=test
      - POSTGRES_DB=mydatabase
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  pg-admin:
    image: dpage/pgadmin4:6
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@email.com
      - PGADMIN_DEFAULT_PASSWORD=admin
      - PGADMIN_LISTEN_PORT=5050
    ports:
      - "5050:5050"

volumes:
  postgres_data:
  keycloak_data:
  mongo_data: